# Generated by Django 6.0.6 on 2026-06-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_product_image_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customers/', verbose_name='Foto de perfil'),
        ),
    ]
