# Generated by Django 6.0.6 on 2026-06-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_customer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
    ]
